Insert into `membership` values ("The Goat Communitte", 2);
Insert into `membership` values ("Stellar", 3);
Insert into `membership` values ("SuperBowl Committee", 1);
Insert into `membership` values ("The Goat Communitte", 1);
Insert into `membership` values ("The Goat Communitte", 10);
Insert into `membership` values ("Stellar", 9);
Insert into `membership` values ("SuperBowl Committee", 5);
Insert into `membership` values ("The Goat Communitte", 5);
Insert into `membership` values ("AI Committee", 3);
Insert into `membership` values ("The Goat Communitte", 7);
Insert into `membership` values ("Stellar", 1);
Insert into `membership` values ("SuperBowl Committee", 7);
Insert into `membership` values ("The Goat Communitte", 6);
Insert into `membership` values ("Stellar", 4);
Insert into `membership` values ("SuperBowl Committee", 4);